export const SET_DANHSACH_PHONG = "SET_DANHSACH_PHONG"
export const SET_DANHSACH_DICHVU = "SET_DANHSACH_DICHVU"
export const SET_DANHSACH_HOADON = "SET_DANHSACH_HOADON"
export const SET_DANHSACH_KHACHHANG = "SET_DANHSACH_KHACHHANG"
export const SET_DANHSACH_HOPDONG = "SET_DANHSACH_HOPDONG"
export const SET_DANHSACH_NHANVIEN = "SET_DANHSACH_NHANVIEN"


// SET values errors
export const SET_PHONG = "SET_PHONG"
export const SET_KHACHHANG = "SET_KHACHHANG"
export const SET_HOPDONG = "SET_HOPDONG"
export const SET_DICHVU = "SET_DICHVU"
export const SET_NHANVIEN = "SET_NHANVIEN"

// THÊM DỮ LIỆU
export const ADD_PHONG = "ADD_PHONG"
export const ADD_KHACHHANG = "ADD_KHACHHANG"
export const ADD_HOPDONG = "ADD_HOPDONG"
export const ADD_DICHVU = "ADD_DICHVU"
export const ADD_NHANVIEN = "ADD_NHANVIEN"