export const SET_DANHSACH_PHONG = "SET_DANHSACH_PHONG"
export const SET_DANHSACH_DICHVU = "SET_DANHSACH_DICHVU"
export const SET_DANHSACH_HOADON = "SET_DANHSACH_HOADON"
export const SET_DANHSACH_KHACHHANG = "SET_DANHSACH_KHACHHANG"
export const SET_DANHSACH_HOPDONG = "SET_DANHSACH_HOPDONG"
export const SET_DANHSACH_NHANVIEN = "SET_DANHSACH_NHANVIEN"
export const SET_DANHSACH_TAISAN = "SET_DANHSACH_TAISAN"


// SET values errors
export const SET_PHONG = "SET_PHONG"
export const SET_KHACHHANG = "SET_KHACHHANG"
export const SET_HOPDONG = "SET_HOPDONG"
export const SET_DICHVU = "SET_DICHVU"
export const SET_NHANVIEN = "SET_NHANVIEN"
export const SET_MAPHONG_PHONG = "SET_KHACHHANG_PHONG";
export const SET_MA_KHACHHANG = "SET_MA_KHACHHANG";
export const SET_TAISAN = "SET_TAISAN"
export const SET_HOADON = "SET_HOADON"

// THÊM DỮ LIỆU
export const ADD_PHONG = "ADD_PHONG"
export const ADD_KHACHHANG = "ADD_KHACHHANG"
export const ADD_HOPDONG = "ADD_HOPDONG"
export const ADD_DICHVU = "ADD_DICHVU"
export const ADD_NHANVIEN = "ADD_NHANVIEN"

// XÓA DỮ LIỆU
export const DELELTE_PHONG = "DELELTE_PHONG"
export const DELETE_KHACHHANG = "DELETE_KHACHHANG"
export const DELETE_HOPDONG = "DELETE_HOPDONG"
export const DELETE_DICHVU = "DELETE_DICHVU"
export const DELETE_NHANVIEN = "DELETE_NHANVIEN"

export const UPDATE_CHISO = 'UPDATE_CHISO'